### ISSUE TITLE
Course activation fails

### ISSUE THREAD

**Issue by pjcarreira** [socialsoftware/quizzes-tutor#116]
The course activation fails after logging-in with the Fénix account.

To reproduce the problem
1. Login with the fénic account
2. Select one of the courses that are presented 
3. On the confirmation box, click "im sure"
4. An error message "Invalid type for course" is displayed

![Screenshot 2020-04-18 at 11 56 37](https://user-images.githubusercontent.com/3728112/79635976-57efb600-816c-11ea-892a-80aab888c0ae.png)
![Screenshot 2020-04-18 at 11 56 45](https://user-images.githubusercontent.com/3728112/79635975-51f9d500-816c-11ea-8b00-1e37b04fc79a.png)

**Comment by ritosilva** [comment]
Fixed!
