### ISSUE TITLE
Domain entities do not implement `equals`

### ISSUE THREAD

**Issue by bsdinis** [socialsoftware/quizzes-tutor#117]
By not implement `equals`, even the most basic value semantic operations are barred to programmers.

This is also error prone, and forces developers to compare Id (obtained via `getId`). Even when this is done, this can also be error-prone, since these are `Integer`s, not `int`s, and values upto `127` compare correctly with `==` but values over this do not.

**Comment by ritosilva** [comment]
Unicity of domain entities is guarantee by JPA through the implementation of the Identity Map pattern.
