### ISSUE TITLE
Quiz closed upon clicking "next"

### ISSUE THREAD

**Issue by hrfmartins** [socialsoftware/quizzes-tutor#120]
Once I started the quiz, answered the first question, and then clicked on the button to go to the next question, I was not prompted by a window to confirm the ''next'', and the quiz instantly closed itself.
After the quiz was finished, I checked and the quiz wasn't in the ''Solved'' page.

**Comment by hugomartins11** [comment]
[Edit] - Just checked and it's showing, and it's saying I answered every question, when I just did one...
