### ISSUE TITLE
Reply to a discussion

### ISSUE THREAD

**Issue by Raimundo82** [socialsoftware/quizzes-tutor#244]
With my user profile i try to reply to a discussion but when i click to submit, the text disappears. I checked on the network tool of the browser and a 500 status code to a POST is being returned.
![Screenshot from 2020-11-18 12-40-25](https://user-images.githubusercontent.com/61196637/99533245-784f4f80-299d-11eb-902e-e5775c9936d1.png)

**Comment by ritosilva** [comment]
I guess it was because the message size >characters. If so, ti is already solved and in production.
