### ISSUE TITLE
Import Code Order Question from XML

### ISSUE THREAD

**Issue by HenriqueLin** [socialsoftware/quizzes-tutor#286]
While doing my 1st part of the project, implement the service to import a ordered Multiple Choice Question from XML, i found a bug when importing a Code Order Question.
In the following test:
https://github.com/socialsoftware/quizzes-tutor/blob/a38161cec73c4bb57710b94eba982a5c7a98d66d/backend/src/test/groovy/pt/ulisboa/tecnico/socialsoftware/tutor/impexp/service/ImportExportCodeOrderQuestionsTest.groovy#L27-L46
if I add another slopDto4 with order=null, the test will fail because of the code below:
https://github.com/socialsoftware/quizzes-tutor/blob/a38161cec73c4bb57710b94eba982a5c7a98d66d/backend/src/main/java/pt/ulisboa/tecnico/socialsoftware/tutor/impexp/domain/QuestionsXmlImport.java#L204
`Integer.valueOf()` will throw a error when receive the string `"null"`.

Henrique Lin - ist194235 - G09

**Comment by ritosilva** [comment]
Fixed in PR. Thanks!
