### ISSUE TITLE
Questions inserted do not show in Quizzes

### ISSUE THREAD

**Issue by AntQuintino** [socialsoftware/quizzes-tutor#318]
Questions inserted do not shows in Quizzes, After several tries, the #19 and #20 questions do not appear in Quizzes. In other quizzes this same questions appear without problem. Urgent, please.

**Comment by ritosilva** [comment]
Is it do to the position of the question in the quiz or to the question itsel?

**Comment by AntQuintino** [comment]
Bom dia,

Problema resolvido. Apaguei o Quizzes e voltei a carregar com questões. Desta vez já me deixou carregar as 20 e não apenas as 18 anteriores.

Obrigado

AQ

**Comment by ritosilva** [comment]
Bom dia,

Se voltar a acontecer, poder-se-ia tentar reproduzir. Por exemplo, ver se
outras questões seriam adicionáveis.

Obrigado,
AR
______
António Rito Silva
Associate Professor, Instituto Superior Técnico, University of Lisbon
Distributed Parallel and Secure Systems, INESC-ID
Rua Alves Redol, 9, Room 535
1000-029 Lisboa, Portugal
Tel.: +351-213 100 263

**Comment by AntQuintino** [comment]
Bom dia

Tentei apagar e voltar a inserir e de facto eram apenas as questões 19 e 20 que não “entravam” no Quizzes. Só resolvi eliminado esse Quizzes e criando um novo.

Obrigado pela pronta reposta

AQ
