### ISSUE TITLE
Quizzes Tutor - Support Users as Teacher and Student of different course executions

### ISSUE THREAD

**Issue by teresabassuncao** [socialsoftware/quizzes-tutor#417]
Bom dia,
Sou monitora da cadeira Modelos de Apoio à Decisão, lecionada no P4 deste ano letivo 2021/22. No entanto, quando faço Log In do Fénix na plataforma Quizzes Tutor, só me aparecem as cadeiras onde fui aluna. Seria possível retificar a situação, para poder gerir a página enquanto docente?
Obrigada,
Teresa Assunção (86889)

**Comment by ritosilva** [comment]
Boa tarde, infelizmente não é possível ter um utilizador como docente e aluno. Podemos ver como alterar, mas creio que as alterações terão alguma dimensão, pelo que ainda levará algum tempo.

**Comment by teresabassuncao** [comment]
Bom dia,
Se for possível, posso ficar só como Docente. Já estou na tese e não terei mais cadeiras enquanto aluna

**Comment by ritosilva** [comment]
Bom dia, ainda terei de ver com atenção qual o impacto das alterações. Amanhã de manhã não será possível.

**Comment by teresabassuncao** [comment]
Okay, obrigada!

**Comment by teresabassuncao** [comment]
Fico à espera de feedback

**Comment by ritosilva** [comment]
Transform the many to many relation between User and CourseExecution into a two entities, Student and Teacher, which correspond to the many to many relations. For instance, the student dashboard will be in the new Student entity.

**Comment by ritosilva** [comment]
Boa tarde, qual é o seu istid? Obrigado.

**Comment by teresabassuncao** [comment]
Boa tarde,
É 86889

**Comment by ritosilva** [comment]
ist186889?

**Comment by teresabassuncao** [comment]
Exato :)

**Comment by ritosilva** [comment]
Pode experimentar se já consegue fazer login como docente? Obrigado.

**Comment by teresabassuncao** [comment]
Já consegui! Muito obrigada

**Comment by ritosilva** [comment]
OK! Vou então fechar o issue e criar um para poder suportar os dois papéis simultaneamente.

**Comment by teresabassuncao** [comment]
Perfeito
