### ISSUE TITLE
External user authentication receives username and password through request params

### ISSUE THREAD

**Issue by EdSwordsmith** [socialsoftware/quizzes-tutor#442]
In [this file](https://github.com/socialsoftware/quizzes-tutor/blob/master/backend/src/main/java/pt/ulisboa/tecnico/socialsoftware/tutor/auth/AuthController.java) the username and password is being received as a request param through a GET request.

This isn't secure, it means the backend logs will show the requests and the username and password of external users. The proper way should be to use a POST request and a dto for the request body that comes with the username and password.

Looking into previous [commits](https://github.com/socialsoftware/quizzes-tutor/blame/1e3e32b29e5ea4bb4450fc8e171be7c81d7ae965/backend/src/main/java/pt/ulisboa/tecnico/socialsoftware/tutor/auth/AuthController.java) this was attempted. However, it was trying to use a GET request with a request body, which isn't possible.

**Comment by ritosilva** [comment]
Thanks!
I'm gonna fix it.
Though this functionality has been used only for tests and in a demo.
