### ISSUE TITLE
Accidental Logout

### ISSUE THREAD

**Issue by henriqueccmac** [socialsoftware/quizzes-tutor#452]
When a user clicks on the logout button, the logout is instant. This means that if a user is currently doing a quiz they can accidentally click on the logout button instead of the end quiz button, therefore annulling their quiz and its respective grade. There should be at least a logout confirmation pop-up (standard practice).

**Comment by ritosilva** [comment]
If a student does a logout during a quiz can login again and continue answering the quiz

**Comment by henriqueccmac** [comment]
That does not change the problem that users can accidentally logout. If a user has a poor connection and can't log back in they will lose their quiz. Or if they have little time left and accidentally press the logout button instead of the end quiz button (they're next to each other), they may not be able to log in and submit the quiz. The user shouldn't lose their work eitherway.

**Comment by ritosilva** [comment]
It is not possible to control all the accidental actions that can be done, for instance, the user can accidentally close the browser tab. If the student does not submit the quiz the answers are not lost because every selection done by the student during the quiz is recorded and the teacher can obtain the sequence of clicks. So no problem if instead of submitting the quiz the student logout. Most of the systems do not ask about a confirmation when logging out, e.g. Fénix, Gmail...

**Comment by henriqueccmac** [comment]
Yes, saving every selection would be ideal, however that doesn't happen. Many users clicked on the logout button accidentally and there is, according to my professor, no way of retrieving my work. Having a simple pop- up avoids a lot of confusion and possibilities of error. Those systems don't have critical information that may be lost if the user logs out. Gmail has draft messages to avoid logout data loss and Fénix also has pop-ups when submitting files for projects or when signing up for classes when creating the semester's schedule.

**Comment by ritosilva** [comment]
When exporting the cvs associated with a quiz all students clicks are listed. You can play with demo (as new) student and demo teacher using the "In Class Quiz One Way".

**Comment by henriqueccmac** [comment]
That creates more work for the teacher for something that could be avoided. The end quiz button has a confirmation pop-up, why shouldn't the logout button have one?
