### ISSUE TITLE
Login is not persisted across refreshes

### ISSUE THREAD

**Issue by hacdias** [socialsoftware/quizzes-tutor#79]
Everytime we refresh the page, we need to login again. It'd be great not to have to login every time we refresh the page.

- Chrome 79
- macOS 10.15.3

**Comment by RageKnify** [comment]
[This StackOverflow answer](https://stackoverflow.com/a/43048031) mentions the main approaches to address this issue in Vue.js.

**Comment by ritosilva** [comment]
fixed
